development:
      host: localhost
      adapter: postgresql
      database: upcoming_development

test: &test
      host: localhost
      adapter: postgresql
      database: upcoming_test
      min_messages: WARNING

production:
      host: localhost
      adapter: postgresql
      database: upcoming_production

cucumber:
  <<: *test
